zuul:
  routes:
    blue:
      url: https://pastebin.com/raw/TEr8Lmv7
    red:
      url: https://pastebin.com/raw/CGrPR43X
    green:
      url: https://pastebin.com/raw/8QN6t4kP
    orange:
      url: https://pastebin.com/raw/7W7mis9e
